package by.AntonDemchuk.ai_pdf_service.entity;

public enum AuditLogAction {
    USER_LOGIN,
    USER_LOGOUT,
    USER_REGISTER,
    USER_UPDATE,
    USER_DELETE,

    FILE_SAVE,
    FILE_DELETE,
    FILE_UPLOAD,
    FILE_DOWNLOAD,
    FILE_REDACTED,
    FILE_SUMMARIZE,
    FILE_ENCRYPT,
    FILE_DECRYPT,
    FILE_UPDATE_METADATA,

    PROCESSING_JOB_CREATE,
    PROCESSING_JOB_DELETE,
    PROCESSING_JOB_UPDATE,
}